name: Android CI

on:
  push:
    branches: [ "ci/cd", "master" ]
  pull_request:
    branches: [ "ci/cd", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Check Java version
        run: java -version  # Verifica que Java 19 está activo
      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew  # Asegurar que Gradle pueda ejecutarse
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build app
        run: ./gradlew build
